### ISSUE TITLE
3.5.1 és 3.6.1 -nél is dobja ezt a hibát: Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra. | wc error: Error processing checkout. Please try again.

### ISSUE THREAD

**Issue by flytech01** [szelpe/woocommerce-barion#70]
Eddig működöktt, hol lehet megnézni a log fájlt valami egyéb hibaüzenetről?
Tudnál segíteni?
Miért romolhatott el?

https://kiralybeata[dot]com

**Comment by oaron** [comment]
Szia,
WooCommerce->Állapot->naplón belül ha a Bariont választod, ír bármilyen hibát?

**Comment by flytech01** [comment]
Kösz, hogy írtál. 
Már működik...
Közvetlenül frissítés után nem tudtam rendelni a fenti hibát dobta. De kb fél óra múlva már működött.
Csak régebbi áprilisi hiba volt a naplóban. De az költöztetés miatt volt szerintem.

04-11-2024 @ 19:55:14 - PreparePayment failed. Errors array: [{"ErrorCode":"CURL_ERROR","Title":"CURL Error #60","Description":"SSL certificate problem: certificate has expired","HappenedAt":"","AuthData":"","EndPoint":"","PaymentId":""}]

**Comment by bsh** [comment]
Ugyan ez:

CRITICAL Uncaught Error: Call to a member function format() on null in /var/www/xy.hu/wp-content/plugins/pay-via-barion-for-woocommerce/includes/class-wc-gateway-barion-request.php:250 CONTEXT: {"error":{"type":1,"file":"/var/www/xy.hu/wp-content/plugins/pay-via-barion-for-woocommerce/includes/class-wc-gateway-barion-request.php","line":250},"backtrace":["","#0 /var/www/xy.hu/wp-content/plugins/pay-via-barion-for-woocommerce/includes/class-wc-gateway-barion-request.php(52): WC_Gateway_Barion_Request->set_payer_account_information()","#1 /var/www/xy.hu/wp-content/plugins/pay-via-barion-for-woocommerce/class-wc-gateway-barion.php(227): WC_Gateway_Barion_Request->prepare_payment()","#2 /var/www/xy.hu/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): WC_Gateway_Barion->process_payment()","#3 /var/www/xy.hu/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment()","#4 /var/www/xy.hu/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(520): WC_Checkout->process_checkout()","#5 /var/www/xy.hu/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout()","#6 /var/www/xy.hu/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#7 /var/www/xy.hu/wp-includes/plugin.php(517): WP_Hook->do_action()","#8 /var/www/xy.hu/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()","#9 /var/www/xy.hu/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax()","#10 /var/www/xy.hu/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#11 /var/www/xy.hu/wp-includes/plugin.php(517): WP_Hook->do_action()","#12 /var/www/xy.hu/wp-includes/template-loader.php(13): do_action()","#13 /var/www/xy.hu/wp-blog-header.php(19): require_once('...')","#14 /var/www/xy.hu/index.php(17): require('...')","#15 {main}","thrown"]}

`
### WordPress Environment ###

WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: hu_HU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian) SVN/1.14.1 mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.1.1n
PHP Version: 8.1.26
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.38-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: wpbc_
Teljes adatbázis mérete: 34.50MB
Adatbázis adatok mérete: 32.11MB
Adatbázis index mérete: 2.39MB
wpbc_woocommerce_sessions: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_woocommerce_api_keys: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_woocommerce_attribute_taxonomies: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_woocommerce_downloadable_product_permissions: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbc_woocommerce_order_items: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_woocommerce_order_itemmeta: Adat: 0.05MB + Index: 0.03MB + Engine InnoDB
wpbc_woocommerce_tax_rates: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbc_woocommerce_tax_rate_locations: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_woocommerce_shipping_zones: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_woocommerce_shipping_zone_locations: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_woocommerce_shipping_zone_methods: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_woocommerce_payment_tokens: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_woocommerce_payment_tokenmeta: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_woocommerce_log: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_actionscheduler_actions: Adat: 0.41MB + Index: 0.18MB + Engine MyISAM
wpbc_actionscheduler_claims: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_actionscheduler_groups: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wpbc_actionscheduler_logs: Adat: 0.27MB + Index: 0.17MB + Engine MyISAM
wpbc_aioseo_cache: Adat: 0.07MB + Index: 0.01MB + Engine MyISAM
wpbc_aioseo_notifications: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_aioseo_posts: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_billingo_documents: Adat: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbc_billingo_partnerhash: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_commentmeta: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wpbc_comments: Adat: 0.02MB + Index: 0.02MB + Engine MyISAM
wpbc_e_events: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_e_notes: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_e_notes_users_relations: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_e_submissions: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_e_submissions_actions_log: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_e_submissions_values: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_gla_attribute_mapping_rules: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_gla_budget_recommendations: Adat: 0.19MB + Index: 0.11MB + Engine InnoDB
wpbc_gla_merchant_issues: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_gla_shipping_rates: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_gla_shipping_times: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_glsr_assigned_posts: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_glsr_assigned_terms: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_glsr_assigned_users: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_glsr_ratings: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_links: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_mystickymenu_contact_lists: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_options: Adat: 2.18MB + Index: 0.07MB + Engine MyISAM
wpbc_postmeta: Adat: 16.39MB + Index: 0.12MB + Engine MyISAM
wpbc_posts: Adat: 11.18MB + Index: 0.05MB + Engine MyISAM
wpbc_redirection_404: Adat: 0.23MB + Index: 0.11MB + Engine InnoDB
wpbc_redirection_groups: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_redirection_items: Adat: 0.02MB + Index: 0.09MB + Engine InnoDB
wpbc_redirection_logs: Adat: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbc_termmeta: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wpbc_terms: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wpbc_term_relationships: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_term_taxonomy: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM
wpbc_usermeta: Adat: 0.01MB + Index: 0.01MB + Engine MyISAM
wpbc_users: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wpbc_vp_woo_pont_mpl_shipments: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_wc_admin_notes: Adat: 0.06MB + Index: 0.00MB + Engine InnoDB
wpbc_wc_admin_note_actions: Adat: 0.05MB + Index: 0.02MB + Engine InnoDB
wpbc_wc_category_lookup: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_wc_customer_lookup: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_wc_download_log: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_wc_orders: Adat: 0.02MB + Index: 0.11MB + Engine InnoDB
wpbc_wc_orders_meta: Adat: 0.08MB + Index: 0.09MB + Engine InnoDB
wpbc_wc_order_addresses: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbc_wc_order_coupon_lookup: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_wc_order_operational_data: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_wc_order_product_lookup: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbc_wc_order_stats: Adat: 0.02MB + Index: 0.05MB + Engine InnoDB
wpbc_wc_order_tax_lookup: Adat: 0.02MB + Index: 0.03MB + Engine InnoDB
wpbc_wc_product_attributes_lookup: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_wc_product_download_directories: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_wc_product_meta_lookup: Adat: 0.02MB + Index: 0.11MB + Engine InnoDB
wpbc_wc_rate_limits: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_wc_reserved_stock: Adat: 0.02MB + Index: 0.00MB + Engine InnoDB
wpbc_wc_tax_rate_classes: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_wc_webhooks: Adat: 0.02MB + Index: 0.02MB + Engine InnoDB
wpbc_wpr_above_the_fold: Adat: 0.02MB + Index: 0.06MB + Engine InnoDB
wpbc_wpr_rocket_cache: Adat: 0.00MB + Index: 0.01MB + Engine MyISAM
wpbc_wpr_rucss_used_css: Adat: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 34
custom_css: 1
elementor_library: 12
elementor_snippet: 1
oembed_cache: 1
page: 15
post: 1
product: 2
review_shortcode: 1
revision: 450
shop_coupon: 5
shop_order_placehold: 15
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Elementor Pro: írta Elementor.com – 3.11.7
Billingo & WooCommerce Official Plugin: írta Billingo Zrt.  – 3.6.4
Yoast Duplicate Post: írta Enrico Battocchi & Team Yoast – 4.5
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: írta Thomas Geiger – 1.20.2
Elementor: írta Elementor.com – 3.24.5
Facebook for WooCommerce: írta Facebook – 3.2.10
Google for WooCommerce: írta WooCommerce – 2.8.5
GTM for WooCommerce FREE - Google Tag Manager Integration: írta Tag Concierge – 1.10.34
HelloPack: írta HelloWP Ltd – 1.2.28
WooCommerce Csomagpontok és Címkék: írta Viszt Péter – 3.4.1.1
Klaviyo: írta Klaviyo
Inc. – 3.4.0

My Sticky Bar: írta Premio – 2.7.7
Barion Payment Gateway for WooCommerce: írta Aron Ocsvari  – 3.7
Redirection: írta John Godley – 5.5.0
HuCommerce | Magyar WooCommerce kiegészítések: írta HuCommerce.hu – 2024.3.0
TikTok: írta TikTok – 1.2.8
UpdraftPlus - Backup/Restore: írta TeamUpdraft
DavidAnderson – 2.24.6.0

WooCommerce Smart COD: írta woosmartcod.com – 1.7.2
WooCommerce.com Update Manager: írta Automattic – 1.0.3
WooCommerce: írta Automattic – 9.3.3

### Inactive Plugins (7) ###

Builder for WooCommerce reviews shortcodes - ReviewShort: írta Tobias Conrad – 1.01.7
Classic Editor: írta WordPress Contributors – 1.6.5
Essential Addons for Elementor: írta WPDeveloper – 6.0.6
Extra Charges To Payment Gateway For WooCommerce (Standard): írta hemsingh1 – 2.0.2.1
Faview - Virtual Reviews for WooCommerce: írta VillaTheme – 1.2.16
Site Reviews: írta Paul Ryley – 7.1.1
WP Rocket: írta WP Media – 3.16.2.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 nap
Level threshold: –
Log directory size: 111 KB

### WC Pages ###

Webshop főoldal: #393 - /uzlet/
Kosár: ❌ Az oldal nem tartalmazza a [woocommerce_cart] rövidkódot vagy a woocommerce/cart blokkot.
Pénztár: ❌ Az oldal nem tartalmazza a [woocommerce_checkout] rövidkódot vagy a woocommerce/checkout blokkot.
Fiókom: #396 - /fiokom/
Általános Szerződési Feltételek: #66 - /aszf/

### Theme ###

Name: Hello Elementor Child
Version: 1.0.0
Author URL: http://example.com/about/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 3.1.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-10-02 12:02:08 +00:00
Options: ✔
Notes: 69
Onboarding: completed

### Action Scheduler ###

Teljesítve: 1 301
Oldest: 2024-09-01 07:30:11 +0000
Newest: 2024-10-02 06:25:26 +0000

Sikertelen: 9
Oldest: 2023-03-29 01:44:13 +0000
Newest: 2024-07-18 08:16:43 +0000

Függőben: 13
Oldest: 2024-10-02 09:09:43 +0000
Newest: 2024-10-03 03:00:00 +0000


### Status report information ###

Generated at: 2024-10-02 06:29:36 +00:00
`
